version: '2'

services:

  app:
    container_name: schedule-app
    build: ./
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker:/var/run/docker"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: armagedon1001
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local


